version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: packaging
    versions:
    - "20.8"
  - dependency-name: markdown
    versions:
    - 3.3.3
  - dependency-name: django-taggit
    versions:
    - 1.3.0
